name: CI

on:
  pull_request:
    branches:
      - "dev/prod"

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Display file contents
        run: cat file.txt

  windows-latest:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Display file contents
        run: type file.txt
